export type Language = 'en' | 'es';
export type LocalizedText = Record<Language, string>;

export interface CircleKey {
  index: number;
  major: string;
  minor: string;
  sharps: number;
  flats: number;
}

export const KEYS: CircleKey[] = [
  { index: 0, major: 'C', minor: 'Am', sharps: 0, flats: 0 },
  { index: 1, major: 'G', minor: 'Em', sharps: 1, flats: 0 },
  { index: 2, major: 'D', minor: 'Bm', sharps: 2, flats: 0 },
  { index: 3, major: 'A', minor: 'F♯m', sharps: 3, flats: 0 },
  { index: 4, major: 'E', minor: 'C♯m', sharps: 4, flats: 0 },
  { index: 5, major: 'B', minor: 'G♯m', sharps: 5, flats: 0 },
  { index: 6, major: 'F♯', minor: 'D♯m', sharps: 6, flats: 0 },
  { index: 7, major: 'D♭', minor: 'B♭m', sharps: 0, flats: 5 },
  { index: 8, major: 'A♭', minor: 'Fm', sharps: 0, flats: 4 },
  { index: 9, major: 'E♭', minor: 'Cm', sharps: 0, flats: 3 },
  { index: 10, major: 'B♭', minor: 'Gm', sharps: 0, flats: 2 },
  { index: 11, major: 'F', minor: 'Dm', sharps: 0, flats: 1 },
];

export const COPY = {
  en: {
    title: 'Circle of Fifths',
    subtitle: 'Click any major or minor key to highlight its diatonic chords',
    ariaLabel: 'Circle of Fifths',
    clickKey: 'Click a key',
    seeChords: 'to see its chords',
    deselect: '↩ click to deselect',
    tonicLegend: 'Tonic (I / i)',
    majorLegend: 'Major chords (IV, V)',
    minorLegend: 'Minor chords (ii, iii, vi)',
    diminishedLegend: 'Diminished (vii° / ii°)',
    diatonicChords: 'Diatonic Chords',
    commonProgressions: 'Common Progressions in',
    generateProgressions: 'Shuffle',
    chorus: 'Chorus',
    bridge: 'Bridge',
    outro: 'Outro',
    verse: 'Verse',
    copy: 'Copy',
    expand: 'Expand',
    collapse: 'Collapse',
    transposeLabel: 'Transpose to:',
    spiceLabels: ['🌶 Spice', '🌶🌶 Spicier', '🔥 Hot!', '↩ Plain'],
    major: 'Major',
    minor: 'Minor',
    diminished: 'diminished',
    relativeMinor: 'Relative minor',
    relativeMajor: 'Relative major',
    showChordDiagrams: 'Show chord diagrams',
    hideChordDiagrams: 'Hide chord diagrams',
    previousPosition: 'Previous position',
    nextPosition: 'Next position',
    previousPositionAll: 'Previous position (all diagrams)',
    nextPositionAll: 'Next position (all diagrams)',
    roles: {
      tonic: 'Tonic',
      supertonic: 'Supertonic',
      mediant: 'Mediant',
      subdominant: 'Subdominant',
      dominant: 'Dominant',
      submediant: 'Submediant',
      leadingTone: 'Leading Tone',
      subtonic: 'Subtonic',
    },
  },
  es: {
    title: 'Círculo de quintas',
    subtitle: 'Haz clic en una tonalidad mayor o menor para resaltar sus acordes diatónicos',
    ariaLabel: 'Círculo de quintas',
    clickKey: 'Haz clic en una tonalidad',
    seeChords: 'para ver sus acordes',
    deselect: '↩ haz clic para deseleccionar',
    tonicLegend: 'Tónica (I / i)',
    majorLegend: 'Acordes mayores (IV, V)',
    minorLegend: 'Acordes menores (ii, iii, vi)',
    diminishedLegend: 'Disminuido (vii° / ii°)',
    diatonicChords: 'Acordes diatónicos',
    commonProgressions: 'Progresiones comunes en',
    generateProgressions: 'Generar nuevos',
    chorus: 'Coro',
    bridge: 'Puente',
    outro: 'Final',
    verse: 'Estrofa',
    copy: 'Copiar',
    expand: 'Expandir',
    collapse: 'Colapsar',
    transposeLabel: 'Transponer a:',
    spiceLabels: ['🌶 Condimentar', '🌶🌶 Más sabor', '🔥 ¡Picante!', '↩ Simple'],
    major: 'Mayor',
    minor: 'Menor',
    diminished: 'disminuido',
    relativeMinor: 'Relativa menor',
    relativeMajor: 'Relativa mayor',
    showChordDiagrams: 'Mostrar acordes de diagramas',
    hideChordDiagrams: 'Ocultar acordes de diagramas',
    previousPosition: 'Posición anterior',
    nextPosition: 'Siguiente posición',
    previousPositionAll: 'Posición anterior (todos)',
    nextPositionAll: 'Siguiente posición (todos)',
    roles: {
      tonic: 'Tónica',
      supertonic: 'Supertónica',
      mediant: 'Mediante',
      subdominant: 'Subdominante',
      dominant: 'Dominante',
      submediant: 'Submediante',
      leadingTone: 'Sensible',
      subtonic: 'Subtónica',
    },
  },
} as const;
